// ── Transaction States ──
export const TxStatus = {
  CREADO: 'CREADO',
  INTENCION_ENVIADA: 'INTENCION_ENVIADA',
  INTENCION_ACEPTADA: 'INTENCION_ACEPTADA',
  DEBITO_PENDIENTE: 'DEBITO_PENDIENTE',
  DEBITO_CONFIRMADO: 'DEBITO_CONFIRMADO',
  CREDITO_ENVIADO: 'CREDITO_ENVIADO',
  EN_CURSO: 'EN_CURSO',
  ACREDITADO: 'ACREDITADO',
  REVERSADO: 'REVERSADO',
  DEVUELTO: 'DEVUELTO',
} as const;

export type TxStatusType = (typeof TxStatus)[keyof typeof TxStatus];

// Valid state transitions
export const TX_TRANSITIONS: Record<string, string[]> = {
  [TxStatus.CREADO]: [TxStatus.INTENCION_ENVIADA, TxStatus.EN_CURSO, TxStatus.REVERSADO],
  [TxStatus.INTENCION_ENVIADA]: [TxStatus.INTENCION_ACEPTADA, TxStatus.REVERSADO],
  [TxStatus.INTENCION_ACEPTADA]: [TxStatus.DEBITO_PENDIENTE, TxStatus.REVERSADO],
  [TxStatus.DEBITO_PENDIENTE]: [TxStatus.DEBITO_CONFIRMADO, TxStatus.REVERSADO],
  [TxStatus.DEBITO_CONFIRMADO]: [TxStatus.CREDITO_ENVIADO, TxStatus.REVERSADO],
  [TxStatus.CREDITO_ENVIADO]: [TxStatus.EN_CURSO, TxStatus.REVERSADO],
  [TxStatus.EN_CURSO]: [TxStatus.ACREDITADO, TxStatus.REVERSADO],
  [TxStatus.ACREDITADO]: [TxStatus.DEVUELTO],
  [TxStatus.REVERSADO]: [],
  [TxStatus.DEVUELTO]: [],
};

// ── Roles ──
export const Role = {
  ADMIN: 'ADMIN',
  OPERATOR: 'OPERATOR',
  MERCHANT: 'MERCHANT',
  VIEWER: 'VIEWER',
} as const;

export type RoleType = (typeof Role)[keyof typeof Role];

// ── COELSA Codes: QRReverso (6200-6206) ──
export const REVERSAL_CODES = {
  '6200': 'REVERSAR OPERACION (TIMEOUT)',
  '6201': 'OPERACIÓN EXPIRADA',
  '6203': 'ERROR CREDITO',
  '6204': 'ERROR DEBITO',
  '6205': 'ERROR COMUNICACIÓN CON ADQUIRIENTE',
  '6206': 'FALLA VALIDACION CONTRA ADQUIRIENTE',
} as const;

// ── COELSA Codes: QROperacionFinalizada (5700-5713) ──
export const OPERATION_FINISHED_CODES = {
  '5700': 'OPERACION CORRECTA',
  '5701': 'OPERACION INEXISTENTE',
  '5702': 'VENDEDOR VIRTUAL INVALIDO',
  '5703': 'CUIT VENDEDOR INCORRECTO',
  '5704': 'CVU VENDEDOR INCORRECTO',
  '5705': 'DEVOLUCION TOTAL',
  '5706': 'ERROR EN EL DEBITO',
  '5708': 'DEVOLUCION PARCIAL',
  '5709': 'ERROR COMUNICACIÓN CON ADQUIRIENTE',
  '5710': 'ADQUIRIENTE DENIEGA OPERACION',
  '5711': 'FALLA VALIDACION CONTRA ADQUIRIENTE',
  '5712': 'REVERSAR OPERACION (TIMEOUT)',
  '5713': 'OPERACIÓN EXPIRADA',
  '5798': 'JSON INCORRECTO',
  '5799': 'ERROR GENERAL',
} as const;

// ── COELSA Codes: QRSolicitudContraCargo (5600-5699) ──
export const REFUND_CODES = {
  '5600': 'CONTRA-CARGO REALIZADO CORRECTAMENTE',
  '5601': 'CREACION PENDIENTE',
  '5602': 'CONTRA-CARGO - INICIADO',
  '5603': 'MONEDA INCORRECTA',
  '5604': 'DESCRIPCION INCORRECTA',
  '5605': 'TIPO ERRONEO',
  '5606': 'ID ERRONEO O INEXISTENTE',
  '5607': 'ID ERRONEO',
  '5608': 'IMPORTE INCORRECTO',
  '5609': 'IMPORTE DISTINTO AL ORIGINAL',
  '5610': 'CUIT DISTINTO AL ORIGINANTE',
  '5611': 'CUENTA DISTINTA AL ORIGINANTE',
  '5612': 'ESTADO INCORRECTO PARA GENERAR CONTRACARGO',
  '5613': 'ESTADO VENDEDOR VIRTUAL INCORRECTO',
  '5614': 'SIN GARANTIA',
  '5615': 'ERROR GENERAL - GARANTIA CREDITO',
  '5616': 'ERROR GENERAL - GARANTIA DEBITO',
  '5617': 'SIN GARANTIA DEBITO',
  '5618': 'SIN GARANTIA CREDITO',
  '5619': 'YA EXISTE UN CONTRA-CARGO REALIZADO',
  '5620': 'PLAZO SUPERADO PARA REALIZAR LA OPERACION',
  '5640': 'GARANTIA CORRECTA',
  '5645': 'ENVIO DE AVISO A CREDITO',
  '5649': 'ACREDITADO CON ERROR GARANTIA',
  '5650': 'ACREDITADO CON GARANTIA',
  '5697': 'ERROR GENERAL - GARANTIA',
  '5698': 'JSON INCORRECTO',
  '5699': 'ERROR GENERAL',
} as const;

// ── COELSA Codes: QRDebin creation (7100-7199) ──
export const DEBIN_CODES = {
  '7100': 'CREACION CORRECTA',
  '7101': 'ERROR DATOS OPERACION',
  '7102': 'NO EXISTE EL CBU VENDEDOR',
  '7103': 'NO EXISTE EL CBU COMPRADOR',
  '7104': 'CUENTA NO ACTIVA',
  '7105': 'MONTO SUPERA VALOR MAXIMO/MINIMO PERMITIDO',
  '7106': 'EXPIRACION INCORRECTA',
  '7107': 'NO ADHERIDO COMO VENDEDOR',
  '7108': 'NO ADHERIDO COMO COMPRADOR',
  '7143': 'BILLETERA INEXISTENTE',
  '7152': 'ID DE OPERACION QR_ID_TRX EXISTENTE',
  '7153': 'BILLETERA NO HABILITADA',
  '7154': 'CVU VENDEDOR NO HABILITADO',
  '7198': 'JSON INCORRECTO',
  '7199': 'ERROR GENERAL VALIDA',
} as const;

// ── COELSA Codes: QRConfirmaDebito (2800-2899) ──
export const CONFIRM_DEBIT_CODES = {
  '2800': 'OPERACION CORRECTA',
  '2899': 'ERROR GENERAL',
} as const;

// ── Merchant Status ──
export const MerchantStatus = {
  PENDING: 'PENDING',
  REGISTERING: 'REGISTERING',
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED',
  DEACTIVATED: 'DEACTIVATED',
} as const;

export const CoelsaStatus = {
  PENDING: 'PENDING',
  REGISTERING: 'REGISTERING',
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED',
} as const;

// ── Settlement ──
export const SettlementFreq = {
  DAILY: 'DAILY',
  WEEKLY: 'WEEKLY',
  MONTHLY: 'MONTHLY',
} as const;

export const SettlementStatus = {
  PENDING: 'PENDING',
  SETTLED: 'SETTLED',
  RECONCILED: 'RECONCILED',
} as const;

// ── QR ──
export const QrType = {
  STATIC: 'STATIC',
  DYNAMIC: 'DYNAMIC',
} as const;

export const QrStatus = {
  ACTIVE: 'ACTIVE',
  EXPIRED: 'EXPIRED',
  DISABLED: 'DISABLED',
} as const;

// ── Timeouts ──
export const COELSA_SYNC_TIMEOUT_MS = 2000; // Our internal limit (<3s COELSA timeout)
export const TRANSACTION_TOTAL_TIMEOUT_MS = 15000;
export const CURRENCY_ARS = '032';
export const COUNTRY_AR = 'AR';
